export const COMPUTE_MEMORY_REPOSITORY_PROVIDER = Symbol('COMPUTE_MEMORY_REPOSITORY_PROVIDER');
export const BENCHMARK_MEMORY_REPOSITORY_PROVIDER = Symbol('BENCHMARK_MEMORY_REPOSITORY_PROVIDER');
export const SOURCE_MONGO_REPOSITORY_PROVIDER = Symbol('SOURCE_MONGO_REPOSITORY_PROVIDER');
export const OBSERVATION_STORE_FACTORIES = Symbol('OBSERVATION_STORE_FACTORIES');
